# Generated by Django 3.1.3 on 2021-02-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbv', '0002_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='adr_info',
        ),
    ]
