# Generated by Django 3.1.3 on 2021-02-05 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbv', '0003_auto_20210205_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='empref',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adrref', to='fbv.employee'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='EMP_INFO',
        ),
    ]
